name: Build

on:
  push:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
    
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: npm run lint

  tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: npm ci
        run: npm ci

      - name: npm run test
        run: npm run test